image:
  file: .gitpod.dockerfile
# vscode:
#   extensions:
#     - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
#     - formulahendry.auto-rename-tag@0.1.0:/DaYBGQJ0OJXTfLl4zwBLA==
#     - HookyQR.beautify@1.5.0:mXo/OcopUVNHHxCPZWwlxQ==
#     - naumovs.color-highlight@2.3.0:6nKORbxgnWjNaN6xACiaQQ==
#     - redhat.java@0.48.0:EYoPv4qnT0DNzzvQHYmZow==
#     - vscjava.vscode-java-debug@0.21.0:2xtBRE0lp5AV4/J7Ptda+g==
#     - vscjava.vscode-maven@0.18.2:qKvEoCRIWFAhA7ftT2EeUw==
