info:
  app:
    name: LocateIPAddress
    description: Geolocation of IP-Addresses
    version: 1.0.0-SNAPSHOT
server:
  servlet:
    session:
      timeout: 60m
vaadin:
  servlet:
    heartbeatInterfall: 10
    closeIdleSession: true
    productionMode: false
    urlMapping: /*
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27000/test
    rest:
      basepath: /api
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    sessions:
      enabled: true

logging:
  level:
    org.springframework.web: ERROR
    com.gmail.michzuerch: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: teachersassistant.log